import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bell,Building2,Users,Workflow,Send,Plus,Check, X, ToggleLeft, ToggleRight} from 'lucide-react';
import './style.css';
const api=(url,options)=>fetch('/api'+url,{headers:{'Content-Type':'application/json'},...options}).then(r=>r.json());
function App(){const [tab,setTab]=useState('dashboard'),[business,setBusiness]=useState(),[members,setMembers]=useState([]),[flows,setFlows]=useState([]),[sendOpen,setSendOpen]=useState(false),[message,setMessage]=useState('Hi {first_name}, we will be closed tomorrow for a public holiday.');const [sent,setSent]=useState(false);
const refresh=async()=>{setBusiness(await api('/business'));setMembers(await api('/members'));setFlows(await api('/automations'))};useEffect(()=>{refresh()},[]);
if(!business)return <div className="loading">Loading your workspace…</div>;
const saveBusiness=async()=>{await api('/business',{method:'PATCH',body:JSON.stringify(business)});alert('Business profile saved')};const toggle=async f=>{await api('/automations/'+f.id,{method:'PATCH',body:JSON.stringify({enabled:!f.enabled})});refresh()};const send=async()=>{await api('/notifications',{method:'POST',body:JSON.stringify({message})});setSent(true)};
return <div className="app"><aside><div className="logo"><span>P</span> pulse.</div><div className="company"><b>{business.name}</b><small>{business.address}</small></div>{[['dashboard','Dashboard',Bell],['members','Members',Users],['automations','Automations',Workflow],['profile','Business profile',Building2]].map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{label}</button>)}</aside><main><header><div><h1>{tab==='dashboard'?'Good morning':tab==='profile'?'Business profile':tab[0].toUpperCase()+tab.slice(1)}</h1><p>{tab==='automations'?'Messages that send themselves at the right moment.':'Manage your members, messages and business from one place.'}</p></div><button className="primary" onClick={()=>{setSent(false);setSendOpen(true)}}><Send size={16}/> Send alert</button></header>{tab==='dashboard'&&<Dashboard members={members} flows={flows} onGo={()=>setTab('automations')}/>} {tab==='members'&&<Members members={members} refresh={refresh}/>} {tab==='automations'&&<Automations flows={flows} toggle={toggle} open={()=>{setSent(false);setSendOpen(true)}}/>}{tab==='profile'&&<Profile business={business} setBusiness={setBusiness} save={saveBusiness}/>}</main>{sendOpen&&<div className="modalback"><div className="modal"><button className="x" onClick={()=>setSendOpen(false)}><X/></button>{sent?<div className="sent"><i><Check/></i><h2>Alert queued</h2><p>Your holiday update will be delivered to all active members.</p><button className="primary" onClick={()=>setSendOpen(false)}>Done</button></div>:<><h2>Send manual alert</h2><p>Use this for holidays, events and special announcements.</p><label>Audience</label><select><option>All active members ({members.length})</option><option>Members expiring soon</option></select><label>Message</label><textarea value={message} onChange={e=>setMessage(e.target.value)}/><div className="modalfoot"><button className="plain" onClick={()=>setSendOpen(false)}>Cancel</button><button className="primary" onClick={send}><Send size={15}/> Send alert</button></div></>}</div></div>}</div>}
function Dashboard({members,flows,onGo}){return <><section className="stats"><Stat value={members.length} label="Active members"/><Stat value="₹4.82L" label="Monthly revenue"/><Stat value={flows.filter(f=>f.enabled).length} label="Active automations"/><Stat value="12" label="Expiring this week"/></section><section className="card welcome"><div><span>SMART MESSAGING</span><h2>Let Pulse keep your members engaged.</h2><p>Welcome new members, remind them before expiry, and bring them back when they go quiet — automatically.</p><button onClick={onGo}>Manage automations</button></div><Workflow size={88}/></section><section className="card"><h2>Recent members</h2>{members.map(m=><div className="member" key={m.id}><b>{m.name}</b><span>{m.plan}</span><em className={m.status}>{m.status}</em><small>Expires {m.expiresAt}</small></div>)}</section></>}; function Stat({value,label}){return <div className="stat"><b>{value}</b><span>{label}</span></div>}
function Automations({flows,toggle,open}){return <><section className="automationhead"><div><span>AUTOMATION CENTER</span><h2>Keep every member in the loop.</h2><p>Turn workflows on and Pulse sends personalized messages for you.</p></div><button className="lime" onClick={open}><Plus size={16}/> Manual alert</button></section><section className="card"><h2>Notification workflows</h2>{flows.map(f=><div className="flow" key={f.id}><div><b>{f.name}</b><p><strong>Trigger:</strong> {f.delay}</p><small>{f.message}</small></div><button className="toggle" onClick={()=>toggle(f)}>{f.enabled?<ToggleRight/>:<ToggleLeft/>}</button><em className={f.enabled?'on':'off'}>{f.enabled?'Live':'Paused'}</em></div>)}</section></>}
function Members({members,refresh}){const [name,setName]=useState('');const add=async()=>{if(!name)return;await api('/members',{method:'POST',body:JSON.stringify({name,phone:'',plan:'Monthly',expiresAt:'2026-10-23'})});setName('');refresh()};return <section className="card"><div className="row"><h2>Members</h2><div><input placeholder="New member name" value={name} onChange={e=>setName(e.target.value)}/><button className="primary" onClick={add}><Plus size={15}/> Add member</button></div></div>{members.map(m=><div className="member" key={m.id}><b>{m.name}</b><span>{m.plan}</span><em className={m.status}>{m.status}</em><small>{m.phone||'Phone pending'}</small></div>)}</section>}
function Profile({business,setBusiness,save}){return <section className="card profile"><h2>Your business</h2><p>These details appear to members in your notifications.</p>{[['name','Business name'],['type','Business type'],['phone','Contact phone'],['email','Reply-to email'],['address','Address'],['timezone','Timezone']].map(([key,label])=><label key={key}>{label}<input value={business[key]||''} onChange={e=>setBusiness({...business,[key]:e.target.value})}/></label>)}<button className="primary" onClick={save}>Save profile</button></section>}
createRoot(document.getElementById('root')).render(<App/>);
